"use client";
import WrapperComponent from "@/components/widgets/WrapperComponent";
import Breadcrumbs from "@/utils/commonComponents/breadcrumb";
import CartContext from "@/context/cartContext";
import AccountContext from "@/context/accountContext";
import SettingContext from "@/context/settingContext";
import { useRouter } from "next/navigation";
import { useContext, useEffect, useMemo, useState } from "react";
import { Col, Row } from "reactstrap";
import SidebarProduct from "./checkoutSidebar/SidebarProduct";
import Link from "next/link";
const blank={label:"home",name:"",phone:"",address:"",city:"",state:"",pincode:""};
const CheckoutContent=()=>{
 const router=useRouter();const {cartProducts,clearCart,getCartLoading,waitForCartSync,refetch:refreshCart,cartSyncError}=useContext(CartContext);const {accountData,refetch:refetchAccount}=useContext(AccountContext);const {convertCurrency}=useContext(SettingContext);
 const addresses=accountData?.address||[];const [selectedId,setSelectedId]=useState("");const [showNew,setShowNew]=useState(false);const [shipping,setShipping]=useState(blank);const [notes,setNotes]=useState("");
 const [quote,setQuote]=useState(null);const [quoteError,setQuoteError]=useState("");const [error,setError]=useState("");const [savingAddress,setSavingAddress]=useState(false);const [submitting,setSubmitting]=useState(false);
 const cartKey=useMemo(()=>JSON.stringify(cartProducts.map(i=>({product_id:i.product_id,quantity:i.quantity,selected_attributes:i.selected_attributes||[]}))),[cartProducts]);
 useEffect(()=>{if(!selectedId&&addresses.length)setSelectedId((addresses.find(a=>a.is_default)||addresses[0]).id);},[addresses,selectedId]);
 useEffect(()=>{if(accountData)setShipping(old=>({...old,name:old.name||accountData.name||"",phone:old.phone||accountData.phone||""}));},[accountData]);
 useEffect(()=>{if(getCartLoading||!cartProducts.length){setQuote(null);return;}const controller=new AbortController();setQuote(null);setQuoteError("");fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:JSON.parse(cartKey)}),signal:controller.signal}).then(async res=>{const data=await res.json();if(!res.ok)throw new Error(data.message||"Unable to confirm prices");setQuote(data);}).catch(e=>{if(e.name!=="AbortError")setQuoteError(e.message);});return()=>controller.abort();},[cartKey,getCartLoading]);
 const setValue=(field,value)=>setShipping(old=>({...old,[field]:value}));
 const saveAddress=async()=>{setSavingAddress(true);setError("");try{const r=await fetch("/api/address",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify(shipping)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Unable to save address");await refetchAccount();setSelectedId(d.data.id);setShowNew(false);setShipping({...blank,name:accountData?.name||"",phone:accountData?.phone||""});}catch(e){setError(e.message)}finally{setSavingAddress(false)}};
 const onSubmit=async e=>{e.preventDefault();if(!selectedId){setError("Please select a saved address or add a new Home/Work address.");return;}if(!quote||submitting||getCartLoading)return;setSubmitting(true);setError("");try{await waitForCartSync();const res=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({address_id:selectedId,notes,payment_method:"cod",items:JSON.parse(cartKey)})});const data=await res.json();if(res.status===401){router.push("/auth/login?next=%2Fcheckout");return;}if(!res.ok){if(res.status===409)await refreshCart();throw new Error(data.message||"Order failed");}clearCart({skipRemote:true});router.replace(`/order/confirmed?order=${encodeURIComponent(data.data.order_number)}`);}catch(e){setError(e.message);}finally{setSubmitting(false);}};
 const fields=[["name","Full name","name"],["phone","Phone number","tel"],["address","Street address / house number","street-address"],["city","City","address-level2"],["state","State","address-level1"],["pincode","PIN code","postal-code"]];
 return <><Breadcrumbs title="Checkout" subNavigation={[{name:"Checkout"}]} /><WrapperComponent classes={{sectionClass:"section-b-space checkout-section-2",fluidClass:"container"}} noRowCol={true}><div className="checkout-page checkout-form"><Row className="g-sm-4 g-3"><Col lg="7"><div className="left-sidebar-checkout"><div className="checkout-detail-box"><div className="checkout-form-section theme-card"><div className="d-flex justify-content-between align-items-center mb-3"><div><h3 className="mb-1">Delivery address</h3><p className="mb-0">Signed in as {accountData?.email}</p></div><button type="button" className="btn btn-solid btn-sm" onClick={()=>setShowNew(v=>!v)}>+ Add New Address</button></div>
 {addresses.length>0&&<Row className="g-3 mb-4">{addresses.map(a=>{const active=selectedId===a.id;return <Col md={6} key={a.id}><label className="d-block h-100" style={{cursor:"pointer"}}><input className="visually-hidden" type="radio" name="saved-address" checked={active} onChange={()=>setSelectedId(a.id)}/><div style={{height:"100%",border:active?"2px solid #97051b":"1px solid #e3e3e3",borderRadius:12,padding:"18px 20px",background:active?"#fff8f9":"#fff",boxShadow:active?"0 5px 18px rgba(151,5,27,.10)":"0 3px 14px rgba(0,0,0,.05)",transition:"all .2s ease"}}><div className="d-flex justify-content-between align-items-center mb-3"><div className="d-flex align-items-center gap-2"><span style={{width:18,height:18,borderRadius:"50%",border:"2px solid #97051b",display:"inline-flex",alignItems:"center",justifyContent:"center"}}>{active&&<span style={{width:8,height:8,borderRadius:"50%",background:"#97051b",display:"block"}}/>}</span><strong style={{textTransform:"capitalize",fontSize:15}}>{a.title||a.label}</strong></div>{a.is_default&&<span style={{fontSize:11,fontWeight:700,color:"#97051b",background:"#fdecef",padding:"5px 9px",borderRadius:20}}>DEFAULT</span>}</div><h5 className="mb-2" style={{fontWeight:600}}>{a.name}</h5><p className="mb-1 text-muted" style={{lineHeight:1.55}}>{a.address}</p><p className="mb-3 text-muted">{a.city}, {a.state} - {a.pincode}</p><div style={{borderTop:"1px solid #eee",paddingTop:12}}><span className="text-muted">Phone: </span><strong>{a.phone}</strong></div></div></label></Col>})}</Row>}
 {!addresses.length&&!showNew&&<div className="alert alert-info">You do not have a saved address yet. Add a Home or Work address to continue.</div>}
 {showNew&&<div className="border rounded p-3 mb-4"><h4 className="mb-3">Add delivery address</h4><div className="mb-3"><label className="form-label d-block">Save as *</label><label className="me-4"><input type="radio" checked={shipping.label==="home"} onChange={()=>setValue("label","home")}/> <span className="ms-1">Home</span></label><label><input type="radio" checked={shipping.label==="work"} onChange={()=>setValue("label","work")}/> <span className="ms-1">Work</span></label></div><Row>{fields.map(([key,label,auto])=><Col md={key==="address"?12:6} key={key}><div className="mb-3"><label className="form-label">{label} *</label><input className="form-control" autoComplete={auto} required value={shipping[key]} onChange={e=>setValue(key,e.target.value)}/></div></Col>)}</Row><button type="button" className="btn btn-solid" disabled={savingAddress} onClick={saveAddress}>{savingAddress?"Saving…":"Save & Use This Address"}</button></div>}
 <form id="customer-order-form" onSubmit={onSubmit}><div className="mb-3"><label className="form-label" htmlFor="order-notes">Order notes (optional)</label><textarea id="order-notes" className="form-control" rows={3} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} /></div><div className="checkout-detail-box mt-4"><div className="checkout-title"><h4>Payment option</h4></div><div className="payment-option"><label className="form-check-label"><input type="radio" checked readOnly className="form-check-input me-2" /> Cash on Delivery (pay when your order arrives)</label></div></div></form>{error&&<div className="alert alert-danger mt-3">{error}</div>}</div></div></div></Col><Col lg="5"><div className="checkout-right-box">{cartProducts.length?<><SidebarProduct quote={quote}/><div className="checkout-details"><div className="order-box"><div className="title-box"><h4>Billing Summary</h4></div><ul className="sub-total"><li>Subtotal <span className="count">{quote?convertCurrency(quote.subtotal):"Checking prices…"}</span></li><li>Shipping <span className="count">{convertCurrency(0)}</span></li></ul><ul className="total"><li className="list-total">Total <span className="count">{quote?convertCurrency(quote.total):"—"}</span></li></ul>{cartSyncError&&<div className="alert alert-danger">{cartSyncError} <button type="button" onClick={refreshCart}>Retry cart sync</button></div>}{quoteError&&<div className="alert alert-danger">{quoteError}</div>}<div className="text-end"><button form="customer-order-form" type="submit" className="btn order-btn btn-solid" disabled={!quote||submitting||getCartLoading||!!cartSyncError||!selectedId}>{submitting?"Placing order…":"Place Order"}</button></div></div></div></>:<div className="checkout-details"><h4>{getCartLoading?"Loading cart…":"Your cart is empty"}</h4><Link href="/collections" className="btn btn-solid mt-3">Continue shopping</Link></div>}</div></Col></Row></div></WrapperComponent></>;
};export default CheckoutContent;
