import nodemailer from "nodemailer";
import path from "node:path";
const adminRecipient = "saraswebsolutions.mdu@gmail.com";
const logoPath = path.join(process.cwd(), "public", "assets", "images", "icon", "logo", "nammakadai", "NammaKadai Name Logo .png");
function transporter(){const user=process.env.EMAIL?.trim(),pass=process.env.EMAIL_PASSWORD?.replace(/\s/g,"");if(!user||!pass)throw new Error("EMAIL and EMAIL_PASSWORD must be configured");return nodemailer.createTransport({host:"smtp.gmail.com",port:465,secure:true,auth:{user,pass}})}
const money=v=>`₹${Number(v||0).toFixed(2)}`;
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const statusLabel=s=>String(s||"placed").replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const attachments=[{filename:"nammakadai-logo.png",path:logoPath,cid:"nammakadai-logo"}];
function shell(title,subtitle,body){return `<!doctype html><html><body style="margin:0;background:#f4f5f7;font-family:Arial,Helvetica,sans-serif;color:#20242a"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f5f7;padding:32px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:650px;background:#fff;border-radius:18px;overflow:hidden;border:1px solid #e9eaed;box-shadow:0 10px 35px rgba(22,28,35,.07)"><tr><td style="padding:24px 30px;background:#fff;border-bottom:4px solid #97051b"><img src="cid:nammakadai-logo" alt="NammaKadai Bharathi Silks" style="display:block;max-width:210px;max-height:64px;width:auto;height:auto"></td></tr><tr><td style="padding:32px 30px 12px"><div style="display:inline-block;padding:6px 10px;background:#fff1f3;color:#97051b;border-radius:20px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px">NammaKadai Order Update</div><h1 style="margin:14px 0 7px;font-size:25px;line-height:1.25;color:#181b20">${esc(title)}</h1><p style="margin:0;color:#747b84;font-size:14px;line-height:1.6">${esc(subtitle)}</p></td></tr><tr><td style="padding:16px 30px 34px">${body}</td></tr><tr><td style="padding:18px 30px;background:#fafafa;border-top:1px solid #eee;color:#92979d;font-size:11px;text-align:center">This is an automated order update from NammaKadai Bharathi Silks.</td></tr></table></td></tr></table></body></html>`}
function orderDetails(order){const rows=(order.items||[]).map(i=>`<tr><td style="padding:12px 0;border-bottom:1px solid #f0f0f0;color:#30343a">${esc(i.productName)}</td><td style="padding:12px 8px;border-bottom:1px solid #f0f0f0;text-align:center;color:#656b73">${i.quantity}</td><td style="padding:12px 0;border-bottom:1px solid #f0f0f0;text-align:right;font-weight:700">${money(i.lineTotal)}</td></tr>`).join("");return `<div style="background:#faf8f8;border:1px solid #f0e7e8;border-radius:12px;padding:18px;margin-bottom:22px"><div style="font-size:12px;color:#8b7377;margin-bottom:5px">ORDER NUMBER</div><div style="font-size:17px;font-weight:700;color:#97051b">#${esc(order.orderNumber)}</div></div><table role="presentation" width="100%" style="font-size:13px;line-height:1.55"><tr><td style="padding:5px 0;color:#777;width:110px">Customer</td><td style="padding:5px 0;font-weight:600">${esc(order.name)}</td></tr><tr><td style="padding:5px 0;color:#777">Phone</td><td style="padding:5px 0">${esc(order.phone)}</td></tr><tr><td style="padding:5px 0;color:#777;vertical-align:top">Delivery</td><td style="padding:5px 0">${esc(`${order.address}, ${order.city}, ${order.state} - ${order.pincode}`)}</td></tr></table><h3 style="font-size:15px;margin:26px 0 8px">Order Items</h3><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="font-size:13px"><tr><th align="left" style="padding:8px 0;color:#8b9198;font-size:11px">ITEM</th><th style="padding:8px;color:#8b9198;font-size:11px">QTY</th><th align="right" style="padding:8px 0;color:#8b9198;font-size:11px">AMOUNT</th></tr>${rows}</table><div style="margin-top:18px;text-align:right;font-size:18px">Total&nbsp; <strong style="color:#97051b">${money(order.total)}</strong></div>`}
export async function sendNewOrderEmails(order,customerEmail){const tx=transporter(),from=`NammaKadai Bharathi Silks <${process.env.EMAIL}>`,html=shell("New order received","A new customer order has been placed successfully.",orderDetails(order));await Promise.all([tx.sendMail({from,to:adminRecipient,subject:`New Order ${order.orderNumber} - ${money(order.total)}`,html,attachments}),tx.sendMail({from,to:customerEmail,subject:`Order confirmed - ${order.orderNumber}`,html:shell("Thank you for your order","We have received your order and will keep you updated as it moves forward.",orderDetails(order)),attachments})])}
export async function sendOrderStatusEmail(order,customerEmail){const label=statusLabel(order.status);const body=`<div style="background:#faf8f8;border:1px solid #f0e7e8;border-radius:12px;padding:20px"><div style="font-size:12px;color:#777">ORDER</div><strong style="display:block;margin-top:4px">#${esc(order.orderNumber)}</strong><div style="height:1px;background:#eadfe1;margin:18px 0"></div><div style="font-size:12px;color:#777">CURRENT STATUS</div><div style="font-size:23px;font-weight:800;color:#97051b;margin-top:5px">${esc(label)}</div></div><p style="margin:20px 0 0;color:#666;font-size:14px">Order total: <strong style="color:#222">${money(order.total)}</strong></p>`;await transporter().sendMail({from:`NammaKadai Bharathi Silks <${process.env.EMAIL}>`,to:customerEmail,subject:`Order ${order.orderNumber} is now ${label}`,html:shell("Order status updated",`Hello ${order.name}, there is an update to your order.`,body),attachments})}


export async function sendRegistrationEmail(customer) {
  const tx = transporter();
  const firstName = esc(customer?.name || "Customer");
  const body = `<div style="background:#faf8f8;border:1px solid #f0e7e8;border-radius:14px;padding:22px;margin:6px 0 22px"><div style="font-size:12px;color:#8b7377;margin-bottom:6px">ACCOUNT CREATED</div><div style="font-size:18px;font-weight:700;color:#20242a">Welcome, ${firstName}</div><p style="margin:10px 0 0;color:#666;font-size:14px;line-height:1.7">Your NammaKadai Bharathi Silks account has been registered successfully. You can now sign in to manage your profile, saved addresses, wishlist and orders.</p></div><table role="presentation" width="100%" style="font-size:13px;line-height:1.6"><tr><td style="padding:6px 0;color:#777;width:90px">Name</td><td style="padding:6px 0;font-weight:600">${firstName}</td></tr><tr><td style="padding:6px 0;color:#777">Email</td><td style="padding:6px 0">${esc(customer?.email || "")}</td></tr></table><p style="margin:24px 0 0;color:#747b84;font-size:13px;line-height:1.7">If you did not create this account, please contact NammaKadai Bharathi Silks.</p>`;
  await tx.sendMail({
    from: `NammaKadai Bharathi Silks <${process.env.EMAIL}>`,
    to: customer.email,
    subject: "Welcome to NammaKadai Bharathi Silks",
    html: shell("Welcome to NammaKadai", "Your customer account is ready to use.", body),
    attachments,
  });
}
