"use client";
import {useEffect,useState} from "react";
export default function AttributesPage(){
 const [items,setItems]=useState([]),[name,setName]=useState(""),[draft,setDraft]=useState({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState({}),[search,setSearch]=useState("");
 const refresh=async()=>{const response=await fetch("/api/admin/attributes",{cache:"no-store"});const json=await response.json();if(!response.ok)throw Error(json.message);setItems(json.data||[])};
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const act=async(url,method,body)=>{setError("");setBusy(true);try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.message);await refresh();return true}catch(e){setError(e.message);return false}finally{setBusy(false)}};
 const filtered=items.filter(item=>`${item.name} ${item.values.map(v=>v.value).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="nk-attributes-page">
 <div className="nk-attributes-header"><div><div className="nk-eyebrow">CATALOG SETTINGS</div><h2>Product attributes</h2><p>Organize sizes, measurements and other product options.</p></div><div className="nk-attribute-total"><strong>{items.length}</strong><span>Attributes</span></div></div>
 {error&&<div className="alert alert-danger" role="alert">{error}</div>}
 <form className="nk-attribute-create" onSubmit={async e=>{e.preventDefault();if(await act("/api/admin/attributes","POST",{name:name.trim()}))setName("")}}><div><label htmlFor="new-attribute">Create new attribute</label><input id="new-attribute" className="form-control" placeholder="e.g. Size, Height, Colour" value={name} onChange={e=>setName(e.target.value)} required/></div><button className="btn btn-primary" disabled={busy||!name.trim()}>+ Add attribute</button></form>
 <div className="nk-attributes-toolbar"><div><h4>Your attributes</h4><span>{items.reduce((n,i)=>n+i.values.length,0)} values across {items.length} attributes</span></div><input className="form-control" aria-label="Search attributes" placeholder="Search attributes or values..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="nk-attributes-grid">{filtered.map(item=><section key={item.uuid} className="nk-attribute-card"><div className="nk-attribute-card-head"><div><div className="nk-attribute-icon">{item.name.charAt(0).toUpperCase()}</div><div><h5>{item.name}</h5><span>{item.values.length} values</span></div></div><button type="button" className="nk-attribute-delete" disabled={busy} onClick={()=>{if(confirm(`Delete ${item.name} and all its values?`))act(`/api/admin/attributes/${item.uuid}`,"DELETE")}}>Delete</button></div>
 <div className="nk-attribute-values">{item.values.slice(0,expanded[item.uuid]?undefined:12).map(value=><span key={value.uuid} className="nk-attribute-value">{value.value}<button type="button" aria-label={`Remove ${value.value}`} title={`Remove ${value.value}`} disabled={busy} onClick={()=>{if(confirm(`Remove ${value.value}?`))act(`/api/admin/attribute-values/${value.uuid}`,"DELETE")}}>×</button></span>)}{!item.values.length&&<p className="nk-attribute-empty">No values yet. Add your first value below.</p>}</div>
 {item.values.length>12&&<button type="button" className="nk-attribute-expand" onClick={()=>setExpanded(v=>({...v,[item.uuid]:!v[item.uuid]}))}>{expanded[item.uuid]?"Show fewer":`Show all ${item.values.length} values`}</button>}
 <form className="nk-attribute-add-value" onSubmit={async e=>{e.preventDefault();if(await act(`/api/admin/attributes/${item.uuid}/values`,"POST",{value:(draft[item.uuid]||"").trim()}))setDraft(v=>({...v,[item.uuid]:""}))}}><input className="form-control" aria-label={`New ${item.name} value`} placeholder={`Add ${item.name.toLowerCase()} value...`} value={draft[item.uuid]||""} onChange={e=>setDraft(v=>({...v,[item.uuid]:e.target.value}))} required/><button disabled={busy||!draft[item.uuid]?.trim()}>+ Add</button></form>
 </section>)}</div>{!filtered.length&&<div className="nk-attribute-no-results">No matching attributes found.</div>}
 </div>
}
