"use client";
import {useEffect,useMemo,useState} from "react";

export default function VariantPricingEditor({productId,assignedAttributes=[],draftGroups,onDraftChange}) {
 const [storedGroups,setStoredGroups]=useState([]),[loading,setLoading]=useState(Boolean(productId)),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const groups=draftGroups ?? storedGroups;
 const setGroups=(update)=>{if(onDraftChange){onDraftChange(old=>{const base=old ?? storedGroups;return typeof update==="function"?update(base):update;});}else{setStoredGroups(update);}};
 const assigned=useMemo(()=>assignedAttributes.filter(a=>a.values?.length),[assignedAttributes]);
 useEffect(()=>{if(!productId)return;let active=true;setLoading(true);fetch(`/api/admin/product-variants/${productId}`).then(r=>r.json()).then(j=>{if(active)setStoredGroups((j.data||[]).map(g=>({...g,options:g.options.map(o=>({selected_attributes:o.selected_attributes}))})));}).catch(()=>{if(active)setNotice("Unable to load variant prices")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[productId]);
 const change=(groupIndex,patch)=>setGroups(old=>old.map((g,i)=>i===groupIndex?{...g,...patch}:g));
 const blankOption=()=>({selected_attributes:assigned.map(a=>({attribute_uuid:a.uuid,value_uuid:""}))});
 const addGroup=()=>setGroups(old=>[...old,{label:"",price:"",sale_price:"",options:[blankOption()]}]);
 const save=async()=>{if(!productId)return;setSaving(true);setNotice("");try{const response=await fetch(`/api/admin/product-variants/${productId}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({groups})});const result=await response.json();if(!response.ok)throw Error(result.message||"Save failed");setNotice("Variant prices saved successfully");if(onDraftChange)onDraftChange([]);}catch(error){setNotice(error.message)}finally{setSaving(false)}};
 if(!assigned.length)return <p className="text-muted">Select product attributes and their values to configure dependent pricing.</p>;
 return <section className="mt-4 border rounded p-3"><h5>Dependent attribute pricing</h5><p className="small text-muted">Create a price group (e.g. Size 24), then add each permitted combination. Click the Add or Update button at the bottom of this product form to save the product and its price groups together.</p>
 {loading?<p>Loading pricing...</p>:<>
 {groups.map((group,index)=><div key={index} className="border rounded p-3 mb-3"><div className="d-flex justify-content-between align-items-center mb-2"><strong>Price group {index+1}</strong><button type="button" className="btn btn-outline-danger btn-sm" onClick={()=>setGroups(old=>old.filter((_,i)=>i!==index))}>Remove group</button></div>
 <div className="row g-2 mb-3"><div className="col-12"><label>Group name (e.g. Size 24)</label><input className="form-control" value={group.label} onChange={e=>change(index,{label:e.target.value})}/></div><div className="col-6"><label>Regular price (₹)</label><input type="number" min="0" step="0.01" className="form-control" value={group.price} onChange={e=>change(index,{price:e.target.value})}/></div><div className="col-6"><label>Sale price (₹)</label><input type="number" min="0" step="0.01" className="form-control" value={group.sale_price} onChange={e=>change(index,{sale_price:e.target.value})}/></div></div>
 {group.options.map((option,optionIndex)=><div key={optionIndex} className="border-top pt-2 mb-2"><div className="row g-2">{assigned.map(attribute=><div className="col-md-4" key={attribute.uuid}><label>{attribute.name}</label><select className="form-select" value={option.selected_attributes.find(a=>a.attribute_uuid===attribute.uuid)?.value_uuid||""} onChange={e=>change(index,{options:group.options.map((o,j)=>j!==optionIndex?o:{selected_attributes:assigned.map(a=>({attribute_uuid:a.uuid,value_uuid:a.uuid===attribute.uuid?e.target.value:o.selected_attributes.find(v=>v.attribute_uuid===a.uuid)?.value_uuid||""}))})})}><option value="">Choose</option>{attribute.values.map(v=><option key={v.uuid} value={v.uuid}>{v.value}</option>)}</select></div>)}</div><button type="button" className="btn btn-link text-danger btn-sm" onClick={()=>change(index,{options:group.options.filter((_,j)=>j!==optionIndex)})}>Remove combination</button></div>)}
 <button type="button" className="btn btn-outline-secondary btn-sm" onClick={()=>change(index,{options:[...group.options,blankOption()]})}>+ Add allowed combination</button></div>)}
 <div className="d-flex gap-2 flex-wrap"><button type="button" className="btn btn-outline-primary" onClick={addGroup}>+ Add price group</button>{productId && <span className="small text-muted align-self-center">Price groups are saved when you click Update at the bottom of the product form.</span>}</div>{notice&&<p role="status" className="mt-2">{notice}</p>}</>}
 </section>;
}
