import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { customerFromRequest } from "@/lib/customerAuth";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const bad=(message,status=422)=>NextResponse.json({message},{status});
const clean=b=>({label:String(b.label||b.title||"").trim().toLowerCase(),name:String(b.name||"").trim(),phone:String(b.phone||"").trim(),address:String(b.address||b.street||"").trim(),city:String(b.city||"").trim(),state:String(b.state||"").trim(),pincode:String(b.pincode||"").trim(),isDefault:Boolean(b.is_default??b.isDefault)});
const valid=a=>(a.label==="home"||a.label==="work")&&a.name&&/^[0-9+()\s-]{8,20}$/.test(a.phone)&&a.address&&a.city&&a.state&&a.pincode;
const out=a=>({id:a.uuid,uuid:a.uuid,title:a.label[0].toUpperCase()+a.label.slice(1),label:a.label,name:a.name,phone:a.phone,street:a.address,address:a.address,city:a.city,state:a.state,pincode:a.pincode,is_default:a.isDefault});
export async function PUT(request,{params}){const c=await customerFromRequest(request);if(!c)return bad("Login required",401);const {id}=await params;const old=await prisma.customerAddress.findFirst({where:{uuid:id,customerUuid:c.uuid}});if(!old)return bad("Address not found",404);const a=clean(await request.json());if(!valid(a))return bad("Please enter a complete Home or Work address");const row=await prisma.$transaction(async tx=>{if(a.isDefault)await tx.customerAddress.updateMany({where:{customerUuid:c.uuid},data:{isDefault:false}});return tx.customerAddress.update({where:{uuid:id},data:a});});return NextResponse.json({message:"Address updated",data:out(row)});}
export async function DELETE(request,{params}){const c=await customerFromRequest(request);if(!c)return bad("Login required",401);const {id}=await params;const old=await prisma.customerAddress.findFirst({where:{uuid:id,customerUuid:c.uuid}});if(!old)return bad("Address not found",404);await prisma.customerAddress.delete({where:{uuid:id}});if(old.isDefault){const next=await prisma.customerAddress.findFirst({where:{customerUuid:c.uuid},orderBy:{createdAt:"desc"}});if(next)await prisma.customerAddress.update({where:{uuid:next.uuid},data:{isDefault:true}});}return NextResponse.json({message:"Address removed"});}
